name: furniture
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.1+1
  flutter_sliding_up_panel: ^2.1.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  mobx: ^2.3.3+2
  nb_utils: ^7.0.2
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/sneakerShopping/
    - assets/images/bahan/
